### ISSUE TITLE
questions about : python scripts/run.py 

### ISSUE THREAD

**Issue by luozhengdong** [xk-huang/OrdinalCLIP#3]
(1)python scripts/run.py --config configs/default.yaml --config configs/base_cfgs/*.yml --config ...
What does this line of code mean? Are the three --config configuration files executed at once, or in three separate executions? The --config ... What does it mean?
(2)what's problem with this? :
Traceback (most recent call last):
  File "scripts/run.py", line 17, in <module>
    from ordinalclip.runner.data import RegressionDataModule
ModuleNotFoundError: No module named 'ordinalclip'

**Comment by xk-huang** [comment]
Hi, Zhengdong! 🤗 
1. It means that the config files are compositional, i.e., you can combine different config files at one job execution.
2. Please follow the installation instructions to “pip install ordinalclip”。

**Comment by luozhengdong** [comment]
Execute ”Single-run mode“ and ”Multi-run mode“ in sequence, or just choose one of these two

**Comment by xk-huang** [comment]
Hi Zhengdong, Sorry for the late reply!
Just choose one of these two. Multi-run mode is used for sweeping over multiple combinations of config.
For the Single-run mode, you might compose different config files in `configs/` folder. For example, you can choose different optimizers `configs/base_cfgs/runner_cfg/optim_sched/optim/`.

**Comment by duyao-art** [comment]
@luozhengdong Hi, have you solved the second problem?
