### ISSUE TITLE
Questions about shifted distributions

### ISSUE THREAD

**Issue by BossunWang** [xk-huang/OrdinalCLIP#4]
Hi expert,
Nice novel method to align embedding latent space to language model.
I'm interest about shifted distributions on figure 4 which test with removing top labels.
How about domain shift experiment? e.g. training on general MORPH II dataset, but test on low resolution MORPH II dataset by resized.
Can the distribution of age prediction be robust?

**Comment by xk-huang** [comment]
Hi, @BossunWang ! Thanks so much for your comment!
We haven't conducted the domain shift experiments. It would be worth experimenting with that setting!
