### ISSUE TITLE
torch

### ISSUE THREAD

**Issue by yunkun123456** [xk-huang/OrdinalCLIP#6]
Excuse me, what version of torch are you using?

**Comment by xk-huang** [comment]
Hi, @yunkun123456!
It's pytorch=1.10.1=py3.8_cuda11.3_cudnn8.2.0_0 in env file https://github.com/xk-huang/OrdinalCLIP/blob/main/environment.yaml.
To prepare env, please check https://github.com/xk-huang/OrdinalCLIP#installation.

**Comment by xk-huang** [comment]
Free free to reopen it if there are any questions!
