### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Xiejiahao233** [xk-huang/OrdinalCLIP#7]
Hello, have you ever encountered a situation where running training code on different machines results in significantly different outcomes, even though the code environments and NVIDIA graphics cards are the same on both machines?

**Comment by xk-huang** [comment]
Hi @Xiejiahao233,

You could try docker (insturctions are written in README) to eliminate the inconsistency in the software layer.

If you want to debug with local environments, you could compare the system info with `transformers-cli env`.

**Comment by Xiejiahao233** [comment]
OK, I'll try it, thank you！

**Comment by xk-huang** [comment]
If you have any question, feel free to re-open the issue.
