### ISSUE TITLE
No config files for Single-run mode

### ISSUE THREAD

**Issue by Magicyu-2015** [xk-huang/OrdinalCLIP#8]
Dear author, thank you for sharing the code with us. I follow up your guidance in the README file. I use docker to conduct the experiment. When I try the python code:
`python scripts/run.py --config configs/default.yaml --config configs/base_cfgs/*.yml --config ...`
However, it got an error. 
<img width="1049" alt="-run py - CrowdCLIP  WSL_ Ubuntu-20 04  - Visual Studio Code" src="https://github.com/user-attachments/assets/54d5b1f6-cea7-40c8-aff4-6677215933e7">
It seems that there is no config files *.yml in the folder configs/base_cfgs/.

**Comment by xk-huang** [comment]
\* means wildcard. Replace it with the files in the dir.
